#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(deref_nullptr)] // (for the tests generated by bindgen)

#[cfg(feature = "run-bindgen")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
#[cfg(not(feature = "run-bindgen"))]
include!("ffi.rs");

pub mod stream;
